In [2]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

In [5]:
df_dsa = pd.read_csv('dados/dados_clientes.csv')
df_dsa.head(10)

   id  idade  renda_anual  pontuacao_gastos
0   1     56        94740                90
1   2     69       136352                50
2   3     46        86617                62
3   4     32       114841                97
4   5     60        36896                51
5   6     25       145729                37
6   7     38        66175                96
7   8     56        27805                87
8   9     36        25237                78
9  10     40       135247                29

In [6]:
#Resumo estatístico

df_dsa[['idade', 'renda_anual', 'pontuacao_gastos']].describe()

            idade    renda_anual  pontuacao_gastos
count  500.000000     500.000000        500.000000
mean    44.732000   81557.166000         48.512000
std     15.239707   36764.379945         29.556946
min     18.000000   20384.000000          0.000000
25%     32.000000   49172.750000         24.000000
50%     45.000000   79219.000000         48.500000
75%     57.000000  113017.250000         73.250000
max     70.000000  149695.000000        100.000000

In [7]:
#Cria padronizador de dados
padronizador = StandardScaler()

In [8]:
dados_padronizados = padronizador.fit_transform(df_dsa[['idade', 'renda_anual', 'pontuacao_gastos']])

In [ ]:
print(dados_padronizados)

[[ 0.74012478  0.35893538  1.40506904]
 [ 1.59401387  1.49192537  0.05039391]
 [ 0.08328703  0.13776654  0.45679645]
 ...
 [-0.31081563  0.32661636  0.18586143]
 [-1.23038848 -1.48706069  1.43893592]
 [-1.03333716 -0.96992912 -0.59307677]]

In [10]:
#definimos um número de clusters (k)
k = 3

In [11]:
#Criamos o modelo k-means
kmeans = KMeans(n_clusters= k)

In [12]:
#Treinamento do modelo com os dados padronizados
kmeans.fit(dados_padronizados)

KMeans(n_clusters=3)

In [13]:
#Atribuimos os rótulos dos cluster aos clientes
df_dsa['cluster'] = kmeans.labels_

In [14]:
df_dsa.head(10)

   id  idade  renda_anual  pontuacao_gastos  cluster
0   1     56        94740                90        0
1   2     69       136352                50        2
2   3     46        86617                62        0
3   4     32       114841                97        2
4   5     60        36896                51        0
5   6     25       145729                37        2
6   7     38        66175                96        0
7   8     56        27805                87        0
8   9     36        25237                78        0
9  10     40       135247                29        2

In [15]:
#Salvamos o resultado em disco
df_dsa.to_csv('dados/segmentados_por_mim.csv', index=False)